// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWcTHldgnHBGh71revIQtMUH9gggTqNnQ',
    appId: '1:27600833255:web:07d221c8ab661aab3cf042',
    messagingSenderId: '27600833255',
    projectId: 'geoplaceflutter',
    authDomain: 'geoplaceflutter.firebaseapp.com',
    databaseURL: 'https://geoplaceflutter-default-rtdb.firebaseio.com',
    storageBucket: 'geoplaceflutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKI-5_4k4w_0VThaI3t4R6HCXs2bSewQo',
    appId: '1:27600833255:android:bea2a9b70bb9904f3cf042',
    messagingSenderId: '27600833255',
    projectId: 'geoplaceflutter',
    databaseURL: 'https://geoplaceflutter-default-rtdb.firebaseio.com',
    storageBucket: 'geoplaceflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ5X_E03viQT8q-B8IoX_51FN_s9y89h0',
    appId: '1:27600833255:ios:c7ead849e1471fda3cf042',
    messagingSenderId: '27600833255',
    projectId: 'geoplaceflutter',
    databaseURL: 'https://geoplaceflutter-default-rtdb.firebaseio.com',
    storageBucket: 'geoplaceflutter.appspot.com',
    iosClientId: '27600833255-o5uetj12pdiacgd9eqhl6e7skbeolj4h.apps.googleusercontent.com',
    iosBundleId: 'geoplaceflutter.davidgonsagainfnet.com.github.geoplaceflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ5X_E03viQT8q-B8IoX_51FN_s9y89h0',
    appId: '1:27600833255:ios:c7ead849e1471fda3cf042',
    messagingSenderId: '27600833255',
    projectId: 'geoplaceflutter',
    databaseURL: 'https://geoplaceflutter-default-rtdb.firebaseio.com',
    storageBucket: 'geoplaceflutter.appspot.com',
    iosClientId: '27600833255-o5uetj12pdiacgd9eqhl6e7skbeolj4h.apps.googleusercontent.com',
    iosBundleId: 'geoplaceflutter.davidgonsagainfnet.com.github.geoplaceflutter',
  );
}
